url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Utah Center for Data Science" # the name of your site, e.g. ACME Corp.

collections:
  news:
    output: true
  programs:
    output: false
  members:
    output: true


show_drafts         : true
limit_posts         : 0
future              : true
unpublished         : true
  

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
exclude:
  - README.md
