url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Utah Center for Data Science" # the name of your site, e.g. ACME Corp.

collections:
  programs:
    output: false
  members:
    output: false
    
plugins:
  - jekyll-datapage-generator
  
# Specifies the automatic page generation for club speakers
page_gen:
# Comment back in once we have a fall speaker
#- data: 'club_speakers.fall_2020'
#  template: 'speaker'
#  name: 'filename'
#  dir: 'club/speakers/fall_2020'

- data: 'club_speakers.summer_2020'
  template: 'speaker'
  name: 'filename'
  dir: 'club/speakers/summer_2020'

defaults:
  -
    scope:
      path: ""
    values:
      layout: single
      header:
        background-image: /assets/img/header-background/zion-shorter.jpg
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
exclude:
  - README.md
