name: Merge Schedule
on:
  pull_request:
    types:
      - opened
      - edited
  schedule:
    # See https://crontab.guru/ for details on scheduling
    - cron: 40 * * * *

jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/merge-schedule-action@v1.x
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}